### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pierzo** [dev-catch/oc-instagram-feed#1]
Hi, is this project finished?

**Comment by voveson** [comment]
Hi @pierzo,

Thanks for your interest in my plugin! I'm not actively working on this project at the moment, but I do intend to maintain it going forward. It is functional and fits the needs that I wrote it for. You can see it in production [here](https://crayonsandcairns.com/be-inspired) (sidebar 9x9 grid) and [here](https://eatsquatmom.com/) (carousel at the bottom of the page). Feel free to incorporate it into your [OctoberCMS](https://octobercms.com/docs) projects if it is useful to you.

Rather than leveraging Instagram's ever increasingly cumbersome API, this project relies on an open-source Instagram web scraper found [here](https://github.com/pgrimaud/instagram-user-feed). As you are probably aware, web scraping is fragile, so this plugin is fragile as well. It works well, and it will continue to work as long as the web scraper continues to work. As I said, I plan to maintain the plugin going forward.

I hope that helps! Feel free to reach out with any other questions you might have!

Cheers,
Vince
